### ISSUE TITLE
4 warnings in demo project

### ISSUE THREAD

**Issue by petr-hybler** [Turkyden/vue-typical#25]
Hello, I am trying to test your package (vue2) but getting error with a sample from your readme file ...

` WARNING  Compiled with 4 warnings`                                                                                                                                           `9:07:59 AM`

` warning  in ./node_modules/vue-typical/dist/vue-typical.es.js`

`"export 'defineComponent' (imported as 't') was not found in 'vue'`

 `warning  in ./node_modules/vue-typical/dist/vue-typical.es.js`

`"export 'h' (imported as 'e') was not found in 'vue'`

 `warning  in ./node_modules/vue-typical/dist/vue-typical.es.js`

`"export 'onMounted' (imported as 'o') was not found in 'vue'`

 `warning  in ./node_modules/vue-typical/dist/vue-typical.es.js`

`"export 'ref' (imported as 'n') was not found in 'vue'`

**Comment by Turkyden** [comment]
Thank you, i will check it ~

**Comment by petr-hybler** [comment]
sure, lemme know should you need more details.. thank you

**Comment by Turkyden** [comment]
> 💡 This library Just support Vue 3

If you are Vue 2, please see the [branch v1](https://github.com/Turkyden/vue-typical/tree/v1) and install [vue-typical@1.6.2](https://github.com/Turkyden/vue-typical/tree/v1)

**Comment by petr-hybler** [comment]
oh I see.. didn't notice that ... thx .. I coded my own already but good to know  .. good you fixed the Readme :)
