### ISSUE TITLE
pen link down

### ISSUE THREAD

**Issue by KnowsCount** [Turkyden/vue-typical#7]
To put it as simply as possible: I cannot visit your pen.

**Comment by Turkyden** [comment]
I need your help !

**Comment by KnowsCount** [comment]
My honour. How can I help?

**Comment by Turkyden** [comment]
Add the codepen ?

**Comment by KnowsCount** [comment]
most certainly. I will take a look in a mo on the methods to creating a vue app on codepen as I have not a clue how to 😂.

**Comment by Turkyden** [comment]
Aha ！https://github.com/Turkyden/vue-typical#contributors

![image](https://user-images.githubusercontent.com/24560160/104846713-e15c3080-5916-11eb-885d-8bbce4373297.png)

**Comment by KnowsCount** [comment]
I need your help here.

I was reading the method to creating a Vue SFCs, and successfully created this: https://codepen.io/pen/editor/vue

however, it says on CodePen

```
Module not found: Error: Can't resolve 'https://cdn.skypack.dev/vue-typical@1.4.0' in '/tmp/codepen/vuejs/src'
```

I cannot comprehend this part. can I use platforms other than codepen?

**Comment by Turkyden** [comment]
> I cannot comprehend this part. can I use platforms other than codepen?

OK, codesandbox ?
